#!/bin/bash
### Simple script to get current Wan IP + Geolocation from Duckduckgo
### v1.3 - removed temp file and awk correction
### v1.2 - Added option to get only Wan IP (-o) and awk output (-a) if specified
### v1.1 - Added colors and myecho functions (available in 'functions' dir in the same repo)

# get script version
_VERS=$(awk '/### v/ {print $0; exit}' $basename $0 |awk '{print $2}')

# test internet access
nc -zw1 duckduckgo.com 443 || { echo "# No Internet Access, exiting.." && exit 1; }

while (( $# )); do
  case $1 in
    -o|--only-ip) _ONLYIP=1; shift ;;
    -h|--help) echo "Usage: $0 [-o|--only-ip]"
      echo "  -o|--only-ip  Get only the IP address"
      echo "  -h|--help     Show this help"
      exit 0
      ;;
    -a|--awk) _AWK=1; shift ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done


# Source colors and myecho functions if available
type _BLU >/dev/null 2>&1 || . /etc/profile.d/01-myecho-colors.sh >/dev/null 2>&1

### Main
# Query duckduckgo.com for "ip address" terms
_TMPRESULT=$(curl -s "https://duckduckgo.com/?q=ip+address" | awk -F'Your IP address is |</a>","AnswerType":"ip"' '{print $2}' | sed -r 's/<a href.*>//; s/\)//; s/\(//')

# Set Vars for proper display
_IP=$(echo "$_TMPRESULT" |awk '{print $1}')
_ZIPCODE=$(echo "$_TMPRESULT" |awk '{print $NF}')
_CITY=$(echo "$_TMPRESULT" |awk -F' in |, ' '{print $2}')
_PROVINCE=$(echo "$_TMPRESULT" |awk -F', ' '{print $2}')
_COUNTRY=$(echo "$_TMPRESULT" |awk -F', | ' '{print $(NF-1)}')

# If only IP is requested, show it and exit
if [[ $_ONLYIP -eq 1 ]]; then
  echo $_IP
  exit 0
fi

_AWKRESULT () {
  echo "########## IP DuckDuck Geoloc ### $_VERS ##########"
  echo "$_TMPRESULT" |awk '{print "# IP: " $1"\n# City: " $3"\n# ZipCode: " $NF"\n# Province: " $4"\n# Country: " $(NF-1)}' |sed 's/,//'
}

_MYRESULT () {
  _MYECHO -t "IP DuckDuck Geoloc ### $_VERS"
  _MYECHO -e "IP" && echo $_IP
  _MYECHO -e "City" && echo $_CITY
  _MYECHO -e "ZipCode" && echo $_ZIPCODE
  _MYECHO -e "Province" && echo $_PROVINCE
  _MYECHO -e "Country" && echo $_COUNTRY
}

# Show results
if [[ $_AWK -eq 1 ]]; then _AWKRESULT; exit 0; fi
if ! type _MYECHO >/dev/null 2>&1; then _AWKRESULT; else _MYRESULT; fi

