#!/bin/bash

# pull all rep at once
pullup (){
_REPOROOT="$HOME/repos"
cd $_REPOROOT
_BLU "####################################################"
_BLU "############### Git Pull all rep UP ################"
ls -d */ | xargs -I ARGS bash -c "echo \"### repo = ARGS\"|tr -d "/"; cd ARGS; git pull; cd $_REPOROOT && echo"
}

# add n push, ex 'gitp "my comment"'
gitp (){
 git add .
 git commit -m "$@"
 git push
}
