#!/bin/bash

_HSTN="srvX"
_NIP="172.17.2.9"
_IPG="$(echo $_NIP|awk -F. '{print $1"."$2"."$3".1"}')"
_IPG1="$(echo $_NIP|awk -F. '{print "10."$2"."$3".1"}')"
_NIP1="$(echo $_NIP|awk -F. '{print "10."$2"."$3"."$4}')"
_IPGT () { ip ro|grep default|awk '{print $3}' ; }
_IPG1T () { ip ro sh|grep via|grep eth1|awk '{print $3}'|uniq ; }

if grep $(hostname) /etc/hosts; then
echo "Modifying hosts and VM hostname..."
sed -i.$(date +"%d%m%Y") "s/^.*$(hostname).*/${_NIP}     ${_HSTN}.zone.local ${_HSTN}/" /etc/hosts
fi
if grep root /etc/passwd |grep $(hostname) ; then sed -i.bak "s/$(hostname)/$_HSTN/" /etc/passwd ; fi
if [ $(hostname) != "$_HSTN" ]; then
echo "Modifying VM Hostname"
hostnamectl set-hostname $_HSTN
fi
if ! grep $_NIP /etc/sysconfig/network; then
sed -i.$(date +"%d%m%Y") "s/^GATEWAY=.*/GATEWAY=$_IPG/" /etc/sysconfig/network
fi
if grep $_NIP /etc/sysconfig/network-scripts/ifcfg-eth0; then
echo "Right IP address already configured in eth0 conf file"
else
echo "Modifying eth0 IP Address..."
ifdown eth0
sleep 2
sed -i "s/^IPADDR.*/IPADDR=$_NIP/" /etc/sysconfig/network-scripts/ifcfg-eth0
ifup eth0
sleep 3
ping -c 1 -w 1 $_IPGT &> /dev/null && echo "eth0 Gateway is Reachable" || echo "eth0 Gateway is UNREACHABLE"
fi
if [ ! -e /etc/sysconfig/network-scripts/ifcfg-eth1 ];then
cp /etc/sysconfig/network-scripts/ifcfg-eth{0,1}
fi
cat > /etc/sysconfig/network-scripts/route-eth1 <<EOF
10.2.0.0/24 via $_IPG1 dev eth1
10.0.0.0/24 via $_IPG1 dev eth1
EOF
if ! grep $_NIP1 /etc/sysconfig/network-scripts/ifcfg-eth1; then
echo "Modifying eth1 IP Address..."
sed -i "s/^IPADDR.*/IPADDR=$_NIP1/" /etc/sysconfig/network-scripts/ifcfg-eth1
sed -i "s/eth0/eth1/" /etc/sysconfig/network-scripts/ifcfg-eth1
ifdown eth1 && ifup eth1
sleep 3
ping -c 1 -w 1 $_IPG1T &> /dev/null && echo "eth1 Gateway is Reachable" || echo "eth1 Gateway is UNREACHABLE"
fi
sleep 1
echo "##### Configured IP Address"
ip -o a|grep eth0|grep -v inet6
echo "##### Configured Hostname"
hostname
echo "##### Configured Hosts"
grep "$_HSTN" /etc/hosts
echo "##### Check install save and spacewalk"
cd /home/userx/
./checkandfix_sauvegarde.sh
cd scripts/
./check_install.sh
./install_client.sh
echo "##### Restarting Zabbix Agent"
systemctl stop zabbix-agent.service
sleep 2
systemctl start zabbix-agent.service
tail -n 20 /VAR/zabbix/log/zabbix_agentd.log
