#!/bin/bash
PARAMS=""
while (( "$#" )); do
  case "$1" in
    -a|--all)
      MY_FLAG='-ltr'
      shift
      ;;
    -f|--folder)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
       MY_FLAG_ARG=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

#./foo -a baz bar --long thing0
ls ${MY_FLAG} ${MY_FLAG_ARG} $PARAMS
