#!/bin/bash

clear
_URL=$1
#if [[ ${_URL} =~ ^.*http.*$ ]]; then
grep -q "^http.*" <<< ${_URL} || exit 1
echo "####### Youtube-DL v2.1 #######"
echo "### url : ${_URL}"
echo "### Press : "
echo "'1' for Video"
echo "'2' for AudioBook"
echo "'Enter' for Music"
echo "'q' to quit"
read -p "> " -n 1 -r
# clear
while true; do
case "$REPLY" in
  1) echo "###########################"
  echo 'Downloading video...'
  screen -S video youtube-dl -o '/data/data/com.termux/files/home/storage/shared/Youtube/%(title)s.%(ext)s' ${_URL}
  break
  ;;
  2) echo "###########################"
  echo 'Downloading AudioBook file...'
  screen -S audiobook youtube-dl -f best -x --audio-format mp3 -o '/data/data/com.termux/files/home/storage/shared/Music/Audiobooks/%(title)s.%(ext)s' ${_URL}
  break
  ;;
  q) echo "###########################"
  echo '..Exiting'
  exit
  ;;
  *) echo "###########################" 
  echo 'Downloading mp3 file...'
  screen -S music youtube-dl -f best -x --audio-format mp3 -o '/data/data/com.termux/files/home/storage/shared/Music/Newz/%(title)s.%(ext)s' ${_URL}
  break
  ;;
esac
done

#fi
