#!/bin/bash
### Termux / Android Chroot Bash script modder
### v0.4 - Quiet mode added
### v0.3 - $TMPDIR support added
# mod '/etc' to '${_ETC}' and '/tmp' to '$TMPDIR' occurences in script for Android

# VARS
_ETCREPLACE="\${_ETC}"
_TMPREPLACE="\${TMPDIR}"
_QUIET=false
_VERS=$(awk '/### v/ {print $0; exit}' $basename $0 |awk '{print $2}')

# Define usage function
usage() {
  echo "Usage: $0 [-h|--help] [-v|--version] [-q|--quiet] <script>"
  echo "  -h, --help    Show this help message"
  echo "  -v, --version Show the version number"
  echo "  -q, --quiet   Run in quiet mode"
  echo "  <script>      The script to modify"
}

# Parse command-line options
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    -v|--version)
      echo "$_VERS"
      exit 0
      ;;
    -q|--quiet)
      _QUIET=true
      shift
      ;;
    *)
      SCRIPT="$1"
      shift
      ;;
  esac
done

# Check for missing script argument
if [ -z "$SCRIPT" ]; then
  echo "Error: missing script argument"
  usage
  exit 1
fi

# Check for non-existent script
if [ ! -f "$SCRIPT" ]; then
  echo "Error: file not found: $SCRIPT"
  exit 1
fi

# Modify script
if grep -q '/etc' "$SCRIPT"; then
    [ "$_QUIET" = false ] && echo "# Modifying '/etc' occurences in $SCRIPT..." && grep -E '/etc' "$SCRIPT"
  sed -i "s/\/etc/${_ETCREPLACE}/g" "$SCRIPT"
    [ "$_QUIET" = false ] && echo "# '/etc' occurences modded to '\${_ETC}' [OK]" && grep "$_ETCREPLACE" "$SCRIPT"
else
    [ "$_QUIET" = false ] && echo "# No '/etc' occurences found in $SCRIPT"
fi

if grep -q '/tmp' "$SCRIPT"; then
    [ "$_QUIET" = false ] && echo "# Modifying '/tmp' occurences in $SCRIPT..." && grep -E '/tmp' "$SCRIPT"
  sed -i "s/\/tmp/${_TMPREPLACE}/g" "$SCRIPT"
    [ "$_QUIET" = false ] && echo "# '/tmp' occurences modded to '\${TMPDIR}' [OK]" && grep "$_TMPREPLACE" "$SCRIPT"
else
    [ "$_QUIET" = false ] && echo "# No '/tmp' occurences found in $SCRIPT"
fi

[ "$_QUIET" = false ] && echo "### Modifications complete."

