#!/bin/bash
### Parse Docker Bitwarden logs and auto blacklist incorrect password tryouts

# vars
_LOGD="/root/blacklist/logs"
[ ! -f "${_LOGD}/.btipnumber" ] && echo '0' >${_LOGD}/.btipnumber 
_OLDFAILNB=$(cat ${_LOGD}/.btipnumber)

# extract bitwarden docker logs and auto ban failed passwords
docker logs bitwarden | grep 'IP:' >${_LOGD}/.btlogs.ips
sleep 1
ACTUALFAILNB=$(cat ${_LOGD}/.btlogs.ips | sort -nu | wc -l)
if [ "$_ACTUALFAILNB" != "$_OLDFAILNB" ]; then
  cat ${_LOGD}/.btlogs.ips|sort -nu |wc -l >${_LOGD}/.btipnumber
  awk -F'IP: ' '/incorrect/ {print $2}' ${_LOGD}/.btlogs.ips |awk '{print $1}' |sort -nu >${_LOGD}/btlogs
  sed -i 's/.$//g' ${_LOGD}/btlogs
  # check if not already in a Blacklist and add to "manual-blacklist" blacklist
  for _IP in $(cat ${_LOGD}/btlogs); do
    if ! blacklist-check $_IP >/dev/null 2>&1; then
    ipset add manual-blacklist "$_IP" && echo "$_IP # blacklisted $(date "+%d-%m-%Y %H:%M:%S")" >> "${_LOGD}/bt-blacklist"
    # telegram alert
    telegram-send "[LTS] Vault Ban # $_IP got blacklisted"
    fi
  done
fi

