#!/bin/bash
echo "##################################"
echo "IPSet Nginx BanScript"
echo "##################################"

##### NEEDS blacklist-check (verify an IP is not blacklisted by IPSET) script to work properly

XTMP=$(mktemp /root/blacklist/nginx-tmp1-XXX)
XTMP2=$(mktemp /root/blacklist/nginx-tmp2-XXX)
XLIST='/root/blacklist/logs/nginx-ban-list'
XBAN='/root/blacklist/logs/nginx-ban-ips'
YOURIPHERE="" #PUT Your IPs here Space separated

# backup and cleanup existing IP lists
[ -f "$XLIST" ] && cp $XLIST{,-$(date "+%Y-%m-%d")}
> $XLIST
[ -f "$XBAN" ] && cp $XBAN{,-$(date "+%Y-%m-%d")}
> $XBAN

### detect common scanner and network tools
echo "# Search for scanner in nginx logs..."
cat /var/log/nginx/access.log|egrep -i 'masscan|CensysInspect|status|bot|nessus|netcraft|admin'|grep -v "127.0.0.1"|grep -oE "\b([0-9]{1,3}.){3}[0-9]{1,3}\b" >$XTMP
zcat /var/log/nginx/access.log*.gz|egrep -i 'masscan|CensysInspect|status|bot|nessus|netcraft|admin'|grep -v "127.0.0.1"|grep -oE "\b([0-9]{1,3}.){3}[0-9]{1,3}\b" >>$XTMP
echo
sed -i "/^3/d; /^200 /d; /^400 /d; /^404 /d; /^2010/d; /^2019/d; /^2020/d; /^2021/d" $XTMP
sort -u $XTMP > $XTMP2 && rm -f $XTMP

echo "# Check for IP address in detected logs..."
for _IP in $(cat "$XTMP2"); do
  if [ ! $(echo "$_IP" | tr '.' ' ' | wc -w) -ne 4 ] ; then
    echo "$_IP" >> $XLIST
  fi
done
rm -f $XTMP2 && sort -u $XLIST > $XBAN
echo
echo "# ... $(cat $XBAN|wc -l) IPs Found"
echo
echo "# Check and add if not already Blacklisted... (need blacklist-check script in path)"
if ! command -v blacklist-check &> /dev/null; then 
  echo "blacklist-check could not be found"
else
  for i in $(cat "$XBAN"); do 
  if ! blacklist-check $i > /dev/null 2>&1; then
    ipset add manual-blacklist $i
    #Telegram alert
    telegram-send "[LTS] NGinX Sniffer # $i got blacklisted"
  fi
  done
fi
echo
echo "# Check and protect $YOURIPHERE 'nomatch' IP"
for YIP in $(echo $YOURIPHERE); do
if ipset list manual-blacklist |grep $YIP|grep nomatch; then 
echo "your IP already has nomatch"
elif ipset list manual-blacklist |grep $YIP; then
ipset del manual-blacklist $YIP
ipset add manual-blacklist $YIP nomatch
echo "your IP $YIP is added to protection"
fi
done
echo
echo
echo "#####################################"
echo "$(ipset list manual-blacklist|wc -l) IPs now Blacklisted by IPSet"
echo "#####################################"
