#!/bin/bash
_LOGD="/root/blacklist/logs"
[ ! -f "${_LOGD}/.failnumber" ] && echo '0' >${_LOGD}/.failnumber
_OLDFAILNB=$(cat ${_LOGD}/.failnumber)
_YOURIPHERE="127.0.0.1" # add your IPs (space separated)

# main check
awk '/ 400 / {print $1}; / 404 / {print $1}; / 500 / {print $1}; / 502 / {print $1}' /var/log/nginx/access.log |sort -nu >${_LOGD}/ng-black.ips.tmp
zcat /var/log/nginx/access.log*.gz | awk '/ 400 / {print $1}; / 404 / {print $1}; / 500 / {print $1}; / 502 / {print $1}' | sort -nu >>${_LOGD}/ng-black.ips.tmp
cat /var/log/nginx/access.log|egrep -i 'masscan|CensysInspect|status|bot|nessus|netcraft|admin'|grep -oE "\b([0-9]{1,3}.){3}[0-9]{1,3}\b" | sort -nu >>${_LOGD}/ng-black.ips.tmp
zcat /var/log/nginx/access.log*.gz|egrep -i 'masscan|CensysInspect|status|bot|nessus|netcraft|admin'|grep -oE "\b([0-9]{1,3}.){3}[0-9]{1,3}\b" | sort -nu >>${_LOGD}/ng-black.ips.tmp
sed -i '/127.0.0.1/d; /^200 /d; /^400 /d; /^404 /d; /^2010/d; /^2019/d; /^2020/d; /^2021/d; /^2022/d' ${_LOGD}/ng-black.ips.tmp

for _IP in $(cat ${_LOGD}/ng-black.ips.tmp); do
  if [ $(echo "$_IP" | tr '.' ' ' | wc -w) = 4 ] ; then
    echo "$_IP" >>${_LOGD}/ng-black.ips.tmp2
  fi
done
_ACTUALFAILNB=$(cat ${_LOGD}/ng-black.ips.tmp2|sort -nu |wc -l)
if [ "$_ACTUALFAILNB" != "$_OLDFAILNB" ]; then
  cat ${_LOGD}/ng-black.ips.tmp2|sort -nu |wc -l >${_LOGD}/.failnumber
  cat ${_LOGD}/ng-black.ips.tmp2|sort -nu >${_LOGD}/ng-black.ips
  rm -f ${_LOGD}/ng-black.ips.tmp2 
  # check if not already in a Blacklist and add to "manual-blacklist" blacklist
  for _IP in $(cat ${_LOGD}/ng-black.ips); do
    if ! blacklist-check $_IP > /dev/null 2>&1; then
    ipset add manual-blacklist "$_IP" && echo "$_IP # blacklisted $(date "+%d-%m-%Y %H:%M:%S")" >> "${_LOGD}/ng-blacklist"
    telegram-send "[LTS] Nginx Ban # $_IP got blacklisted"
    fi
  done
fi

# My IP protect
# Check and protect $YOURIPHERE 'nomatch' IP
for YIP in $(echo $_YOURIPHERE); do
  if ipset list manual-blacklist |grep $YIP|grep -q nomatch; then
    echo #"your IP already has nomatch"
  else
  if ipset list manual-blacklist |grep -q $YIP; then
    ipset del manual-blacklist $YIP
    ipset add manual-blacklist $YIP nomatch
    echo "your IP $YIP is added to protection"
  fi
fi
done
